project:
  type: website

website:
  title: "E155ProjectPortfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - documentation.qmd
      - FPGA.qmd
      - MCU.qmd
      - Specifications.qmd
      - team.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



